### ISSUE TITLE
Unable to find AWS CLI

### ISSUE THREAD

**Issue by diegosasw** [localstack-dotnet/localstack-awscli-local#3]
## Expected Behavior
`awslocal kinesis list-streams` should list kinesis streams

## Actual Behavior
`awslocal kinesis list-streams` returns the error
```
$ awslocal kinesis list-streams
ERROR: Unable to find aws cli
```

## Steps to Reproduce the Problem

  1. Install dotnet 5 SDK 5.0.200
  2. Install AWS CLI
  3. Install LocalStack tool `dotnet tool install --global LocalStack.AwsLocal`
  4. Run `awslocal kinesis list-streams`

## Specifications

  - Version: 1.3.0
  - Platform: Windows 10 64bit

See
```
$ aws --version
aws-cli/2.1.27 Python/3.7.9 Windows/10 exe/AMD64 prompt/off

$ awslocal
Thin wrapper around the "aws" command line interface (CLI) for use with LocalStack.

The "awslocal" CLI allows you to easily interact with your local services without
having to specify "--endpoint-url=http://..." for every single command.

Example:
Instead of the following command ...
aws --endpoint-url=https://localhost:4568 --no-verify-ssl kinesis list-streams
... you can simply use this:
awslocal kinesis list-streams

Options:
  Run "aws help" for more details on the aws CLI subcommands.

$ awslocal kinesis list-streams
ERROR: Unable to find aws cli

$ dotnet --version
5.0.200
```

And the tools installed globally
```
$ dotnet tool list -g
Package Id                      Version      Commands
------------------------------------------------------------------------
amazon.lambda.testtool-3.1      0.11.1       dotnet-lambda-test-tool-3.1
amazon.lambda.tools             5.0.1        dotnet-lambda
dotnet-ef                       5.0.3        dotnet-ef
localstack.awslocal             1.3.0        awslocal
```

**Comment by Blind-Striker** [comment]
Hi, @diegosasw I tried to reproduce your case on Powershell, cmd, and gitbash. Although our environments are similar (.net version, tool version) mine was a success. it was a quick test though and I hadn't started a LocalStack instance. 
I will check it in more detail tomorrow.

```
E:\>awslocal kinesis list-streams

Could not connect to the endpoint URL: "http://localhost:4566/"
```

**Comment by Blind-Striker** [comment]
Hmmm, one of my friends has tried and reproduced your case. It probably related to how I get aws cli path env variable

**Comment by Blind-Striker** [comment]
Ok, apparently after a certain version, they changed aws cli executable from aws.cmd to aws.exe. It's been a long time that I use aws cli on windows environment since I started to use WSL 2. I'll fix it as soon as possible.

**Comment by Blind-Striker** [comment]
Hi @diegosasw it should be fixed with the new version.

https://github.com/localstack-dotnet/localstack-awscli-local/releases/tag/v1.3.0.1

Could you please check it and inform me if any other problem.
